<a href="https://colab.research.google.com/github/Kt7mmm/Unsupervised-Deep-Embedding-for-Clustering-Analysis-DEC-with-Reuters-Dataset-/blob/main/Reuters10k.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/Kt7mmm/Unsupervised-Deep-Embedding-for-Clustering-Analysis-DEC-with-Reuters-Dataset-.git

Cloning into 'Unsupervised-Deep-Embedding-for-Clustering-Analysis-DEC-with-Reuters-Dataset-'...
remote: Enumerating objects: 314, done.
remote: Counting objects: 100% (314/314), done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 314 (delta 157), reused 302 (delta 150), pack-reused 0
Receiving objects: 100% (314/314), 3.47 MiB | 3.37 MiB/s, done.
Resolving deltas: 100% (157/157), done.


In [2]:
%cd /content/Unsupervised-Deep-Embedding-for-Clustering-Analysis-DEC-with-Reuters-Dataset-
!python setup.py install

/content/Unsupervised-Deep-Embedding-for-Clustering-Analysis-DEC-with-Reuters-Dataset-
/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running install
/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

   

In [3]:
!pip install -r requirements.txt

Obtaining ptsdae from git+https://github.com/vlukiyanov/pt-sdae.git#egg=ptsdae (from -r requirements.txt (line 19))
  Cloning https://github.com/vlukiyanov/pt-sdae.git to ./src/ptsdae
  Running command git clone --filter=blob:none --quiet https://github.com/vlukiyanov/pt-sdae.git /content/Unsupervised-Deep-Embedding-for-Clustering-Analysis-DEC-with-Reuters-Dataset-/src/ptsdae
  Resolved https://github.com/vlukiyanov/pt-sdae.git to commit 57b2c544cd3f989e87a3037d5ea0bb3a59d05eed
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 9.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 20.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 10.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 16.6 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda

In [4]:
!pip install datasets


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 7.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 8.7 MB/s eta 0:00:00


In [5]:
# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
%cd /content/Unsupervised-Deep-Embedding-for-Clustering-Analysis-DEC-with-Reuters-Dataset-/examples/reuters-10k

/content/Unsupervised-Deep-Embedding-for-Clustering-Analysis-DEC-with-Reuters-Dataset-/examples/reuters-10k


In [7]:
!python reuters.py --cuda True --batch-size 256 --pretrain-epochs 250 --finetune-epochs 450 --mat-file reuters10k.mat

Pretraining stage.
/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:143: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
100% 40/40 [00:01<00:00, 25.80batch/s, epo=0, lss=1.056713, vls=-1.000000]
100% 40/40 [00:01<00:00, 37.19batch/s, epo=1, lss=0.997775, vls=1.041334]
100% 40/40 [00:01<00:00, 33.39batch/s, epo=2, lss=1.010484, vls=1.013685]
100% 40/40 [00:01<00:00, 31.95batch/s, epo=3, lss=1.006894, vls=1.003416]
100% 40/40 [00:01<00:00, 36.26batch/s, epo=4, lss=0.996615, vls=0.996596]
100% 40/40 [00:01<00:00, 35.52batch/s, epo=5, lss=0.989073, vl

In [12]:
# Run the plotting script
!python generatePlots.py --cuda True --mat-file reuters10k.mat --target-cluster 0

Final DEC accuracy: 0.4711
Top 10 scoring elements in each cluster:
[[7453  681 8247 6466 4363 4139 9169 6702 9836  856]
 [5184 1812 3389 7311 6924 6999 1113 6305 5483 9628]
 [3992 9181  556 8916 8655 9461 5139 5395 7932 7474]
 [3102 8027 1137  422 1434 4056 2750 9322  366 1182]
 [9635 3415 1710 7597 8823 3479 1901 9150 7937  987]
 [2710 8049 6567 1947  686  565 8045 5935 5649 2689]
 [4631 8735  692 8674 6105 2713 3740 3959 1474 1300]
 [5482 2662 4447 7283 5806 8061 2752 2694 6077 7170]
 [7104 7602 9918 1544 3207 9290 4785 8385 4797 6320]
 [6449 6811 1541 5930 7165 9063 7773 1419  822  352]]
Figure(1200x1000)
Writing out confusion diagram with UUID: e444e64f226a47968ea9c66a3ba12554


In [16]:
!python top10elements.py --cuda False --mat-file reuters10k.mat


Top 10 scoring elements in each cluster:

Cluster 0:
Index 7453: [0. 0. 0. ... 0. 0. 0.]
Index 681: [0. 0. 0. ... 0. 0. 0.]
Index 8247: [0. 0. 0. ... 0. 0. 0.]
Index 6466: [0. 0. 0. ... 0. 0. 0.]
Index 4363: [0. 0. 0. ... 0. 0. 0.]
Index 4139: [0. 0. 0. ... 0. 0. 0.]
Index 9169: [0. 0. 0. ... 0. 0. 0.]
Index 6702: [0. 0. 0. ... 0. 0. 0.]
Index 9836: [0. 0. 0. ... 0. 0. 0.]
Index 856: [0. 0. 0. ... 0. 0. 0.]

Cluster 1:
Index 5184: [0. 0. 0. ... 0. 0. 0.]
Index 1812: [0. 0. 0. ... 0. 0. 0.]
Index 3389: [0. 0. 0. ... 0. 0. 0.]
Index 7311: [0. 0. 0. ... 0. 0. 0.]
Index 6924: [0. 0. 0. ... 0. 0. 0.]
Index 6999: [0. 0. 0. ... 0. 0. 0.]
Index 1113: [0. 0. 0. ... 0. 0. 0.]
Index 6305: [0. 0. 0. ... 0. 0. 0.]
Index 5483: [0. 0. 0. ... 0. 0. 0.]
Index 9628: [0. 0. 0. ... 0. 0. 0.]

Cluster 2:
Index 3992: [0. 0. 0. ... 0. 0. 0.]
Index 9181: [0. 0. 0. ... 0. 0. 0.]
Index 556: [0. 0. 0. ... 0. 0. 0.]
Index 8916: [0. 0. 0. ... 0. 0. 0.]
Index 8655: [0. 0. 0. ... 0. 0. 0.]
Index 9461: [0. 0. 0. ... 